# yaml file to configure the Landsat C2 SR & ST parameters for this repository workflow

# The following parameters are required to be set by the user unless otherwise indicated.

local_settings:
- data_dir: "~/Documents/GitHub/Landsat_C2_SRST/data_acquisition/in/" # point to the directory where your location information is stored - this path must end with a '/'
- location_file: "locs_test_2.csv" # name of the file that contains the location information
- unique_id: "id" # this is the column that stores the unique identifier for each site, should not contain any special characters
- latitude: "Latitude" # this is the column that stores the latitude of the site, must be in decimal degrees
- longitude: "Longitude" # this is the column that stores the longitude of the site, must be in decimal degrees
- location_crs: "EPSG:4326" # this is the coordinate reference system of the location data, must be in EPSG format (e.g. EPSG:4326)
- polygon: 'False' # optional. True or False - if True, you have lake polygon shapefiles for each site.
- poly_dir: "" # optional. point to the directory where your lake polygon shapefiles are stored - this path must end with a '/'
- poly_file: "" # optional. name of the shapefile that contains the lake polygons. 

google_settings:
- proj: "TEST" # this is a short name for file naming conventions. All output files will include this prefix.
- proj_folder: "TEST" # this is the folder name where the GEE data will be save to Google Drive. If it doesn't exist, it will be created.


###############################################################################
# The following parameters are optional and have default values listed below. 
# If these key-values remain unaltered, data will be acquired for the entire satellite data record at the specified location only.

temporal_settings:
- start_date: "1983-01-01" # earliest data of satellite data to be acquired; earliest data available is 1983-01-01
- end_date: "today" # latest date of satellite data to be acquired; if 'today' is used, the date will be set to the current date

spatial_settings: 
- extent: "site" # options: "site", "polygon", "polycenter", "site+polygon", etc - only site/polygon function right now
- site_buffer: 90 # buffer distance in meters around the site

gee_settings:
- cloud_filter: "True" # True or False - if True, scenes will be filtered by scene-level cloudy value provided in the metadata
- cloud_thresh: 95 # scenes with a cloud value greater than this threshold will be filtered out
- water_detection: "DSWE" # "DSWE" is currently the only option for water detection. Future iterations may include Peckel water instance or another method.
- DSWE_setting: "1" # DSWE 1 only summarizes high confidence water pixels. While DSWE 1 is the only option, future iterations may also incorporate DSWE 3, which indicates possibly-vegetated pixesl (aka, macrophytes)


